# Generated by Django 4.2.5 on 2023-09-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_districts', '0002_rename_district_name_en_districts_district_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='district_en',
            new_name='district_name_en',
        ),
        migrations.RenameField(
            model_name='districts',
            old_name='district_ru',
            new_name='district_name_ru',
        ),
        migrations.RenameField(
            model_name='districts',
            old_name='district_uz',
            new_name='district_name_uz',
        ),
    ]
